#!/bin/bash
set -x
VAGRANT_BUILD_PATH=~/Dokumente/Schule/Bento-Boxen/packer-ubuntu-1604-de
if [ -z $2 ]
then
	COMMAND=$1
else
	COMMAND=$2
	VAGRANT_PATH=$VAGRANT_BUILD_PATH/vagrant-$1/
fi
cd $VAGRANT_PATH
if [ $COMMAND == "neu" ]
then
	read -p "Are you sure? " -n 1 -r
	echo    # (optional) move to a new line
	if [[ $REPLY =~ ^[Yy]$ ]]
	then
		vagrant destroy --force
		if [ -z $2 ]
		then
			vagrant up rdf
		else
			cd $VAGRANT_BUILD_PATH
			ansible-playbook ansible-local/playbook.yml  --extra-vars="type=$1"
			cd -
			vagrant up rdf
			vagrant ssh rdf
		fi
	fi
else
	if [ $COMMAND == "ssh" ]
	then
		vagrant up rdf || true
	fi
	vagrant $COMMAND rdf
fi
cd -
