#!/bin/bash
set -x
VAGRANT_BUILD_PATH=~/Dokumente/Schule/Bento-Boxen/packer-ubuntu-1604-de
#Falls kein zweites Kommando angegeben setze vagrant Command aus dem zustarten.
#Pfad dann im Buildpath um dort zu starten. Type ist desktop.
if [ -z $2 ]
then
	COMMAND=$1
	VAGRANT_PATH=$VAGRANT_BUILD_PATH
	TYPE=desktop
else
	COMMAND=$2
	VAGRANT_PATH=$VAGRANT_BUILD_PATH/vagrant-$1/
	TYPE=$1
fi
if [ ! -d $VAGRANT_PATH ]
then
	mkdir -p $VAGRANT_PATH
fi
OLD=$PWD
cd $VAGRANT_PATH
if [ $COMMAND == "neu" ]
then
	read -p "Are you sure? " -n 1 -r
	echo    # (optional) move to a new line
	if [[ $REPLY =~ ^[Yy]$ ]]
	then
		vagrant destroy --force
		# Falls ein Type angegeben wurde neuen suchen
		# Ansonsten im Buildverzeichnie einfach starten
		if [ ! -z $2 ]
		then
			cd $VAGRANT_BUILD_PATH
			set -e
			ansible-playbook ansible-local/playbook.yml  --extra-vars="type=$TYPE"
			set +e
			cd -
		fi
		vagrant up rdf
		vagrant ssh rdf
	fi
else
	if [ $COMMAND == "ssh" ]
	then
		vagrant up rdf || true
	fi
	vagrant $COMMAND rdf
fi
cd $OLD
