---
- src: geerlingguy.packer-debian
- src: geerlingguy.nfs
- src: tersmitten.locales
- src: tersmitten.timezone
- src: cmprescott.dnsmasq
- src: toopy.lxc-dev
- src: gantsign.keyboard
- src: gantsign.lightdm
- src: https://github.com/gantsign/ansible-role-xdesktop/archive/2.2.0.tar.gz
  name: gantsign.xdesktop
- src: tersmitten.pip
- src: tersmitten.virtualenv
- src: tersmitten.ansible
