---
- src: geerlingguy.packer-debian
- src: geerlingguy.nfs
- src: geerlingguy.nodejs
- src: tersmitten.locales
- src: tersmitten.timezone
- src: cmprescott.dnsmasq
- src: toopy.lxc-dev
- src: gantsign.keyboard
- src: gantsign.lightdm
- src: https://github.com/gantsign/ansible-role-xdesktop/archive/2.2.0.tar.gz
  name: gantsign.xdesktop
- src: gantsign.terminator
- src: tschifftner.firefox
- src: gantsign.java
- src: arknoll.selenium
- src: franklinkim.environment
- src: cmprescott.chrome
- src: gantsign.default-web-browser
- src: gantsign.atom
- src: gantsign.atom-packages
- src: gantsign.golang
- src: gantsign.oh-my-zsh
- src: tersmitten.pip
- src: tersmitten.virtualenv
- src: tersmitten.ansible
