---
- src: geerlingguy.packer-debian
- src: geerlingguy.nfs
- src: tersmitten.locales
- src: tersmitten.timezone
- src: cmprescott.dnsmasq
- src: toopy.lxc-dev
- src: gantsign.keyboard
- src: tersmitten.pip
- src: tersmitten.virtualenv
- src: tersmitten.ansible
